export interface Measurement {value:string|number|null; unit?:string|null; source?:string|null; sourceUrl?:string; evidence:string; nullReason?:string; display?:string; conditions?:string}
export interface ElementData {z:number;symbol:string;name:string;matId:string;period:number;group:number|null;block:string;category:string;recordStatus:'CURATED'|'BASELINE';chapterPath:string|null;atomicWeight:string|number|null;provenance:Record<string,Measurement>}
export interface RecordData {id:string;key:string;mat:string|null;title:string;section:string;lane:string}
export interface Chapter extends RecordData {body:string;bodyHash:string;header:Record<string,unknown>;structured:{path:string;data:unknown}[];assets:string[];sources:Record<string,unknown>[];missingSources:string[];counts:Record<string,number>;reviewStatus:string}
export interface MATData {elements:ElementData[];records:RecordData[];metadata:{title:string;missingSources:string[];notice:string};catalog:{sources:{id:string;url:string;sha256:string}[]}}
export const assetURL=(p:string)=>import.meta.env.BASE_URL+p.replace(/^\/+/,'');
async function getJSON(path:string,signal?:AbortSignal){const r=await fetch(assetURL('data/publication/generated/'+path),{signal});if(!r.ok)throw new Error('Publication data unavailable ('+r.status+').');if(!r.headers.get('content-type')?.includes('json'))throw new Error('Server returned a page instead of publication data. Rebuild Studio.');return r.json()}
export async function loadData():Promise<MATData>{const [e,records,metadata]=await Promise.all([getJSON('publication-elements.json'),getJSON('publication-records.json'),getJSON('publication-metadata.json')]);if(!Array.isArray(e.elements)||e.elements.length!==118||!Array.isArray(records))throw new Error('Incomplete publication catalogue.');return {elements:e.elements,records,metadata,catalog:e.catalog}}
export async function loadChapter(r:RecordData,signal?:AbortSignal):Promise<Chapter>{const d=await getJSON('chapters/'+r.key+'.json',signal);if(d.id!==r.id||typeof d.body!=='string')throw new Error('Invalid chapter data.');return d}
export function filterElements(elements:ElementData[],query:string,status:string){const q=query.trim().toLowerCase();return elements.filter(e=>(status==='all'||e.recordStatus===status)&&(!q||[e.name,e.symbol,e.matId,e.category].some(v=>v.toLowerCase().includes(q))||String(e.z)===q))}

