export const propertyKeys={atomicWeight:'atomic_weight',electronConfiguration:'electron_configuration',electronegativity:'electronegativity',firstIonizationEnergy:'first_ionization_energy',phase:'phase',meltingPoint:'melting_point',boilingPoint:'boiling_point',density:'density',oxidationStates:'oxidation_states'};
export function properties(el){return Object.fromEntries(Object.entries(propertyKeys).map(([k,v])=>[v,el[k]]))}
const val=m=>String(m.display??m.value??m.nullReason??'UNAVAILABLE');
export function baselineTable(el){return '| Property | Value | Unit | Conditions | Evidence | Source |\n|---|---|---|---|---|---|\n'+Object.keys(propertyKeys).map(k=>{const m=el[k];return '| '+k+' | '+val(m)+' | '+(m.unit||'dimensionless / text')+' | '+(m.conditions||'See source')+' | '+m.evidence+' | '+(m.source||'UNAVAILABLE')+' |'}).join('\n')}
export function enrichBaselineChapter(text,el){
 text=text.replace(/symbol: "[^"]+"\n/,'symbol: "'+el.symbol+'"\natomic_number: '+el.z+'\n');
 text=text.replace(/\| Standard atomic weight \|[^\n]*/,'| Standard atomic weight | '+val(el.atomicWeight)+' | '+el.atomicWeight.evidence+' | CIAAW-2024 |');
 text=text.replace(/Electronic configuration: \*\*[^*]+\*\*/,'Electronic configuration: **'+val(el.electronConfiguration)+'** ('+el.electronConfiguration.evidence+'; PUBCHEM-PERIODIC).');
 text=text.replace(/# 9\. Physical Properties[\s\S]*?(?=# 10\.)/,'# 9. Physical Properties\n\n'+baselineTable(el)+'\n\nAbundances remain UNAVAILABLE pending source-specific curation. Standard atomic weight is dimensionless; isotope mass numbers are not substituted for it. For helium, a melting point needs pressure-specific qualification.\n\n---\n\n');
 text=text.replace(/# 33\. Sources[\s\S]*?(?=# 34\.)/,'# 33. Sources\n\n- [PubChem periodic table download](https://pubchem.ncbi.nlm.nih.gov/rest/pug/periodictable/JSON), retained 2026-09-08 as PUBCHEM-PERIODIC.\n- [CIAAW standard atomic weights](https://www.ciaaw.org/atomic-weights.htm), retained 2026-09-08 as CIAAW-2024.\n- Catalogue snapshot hashes and property-level evidence are recorded in data/catalog/sources and data/catalog/elements-baseline.json.\n\n---\n\n');
 text=text.replace(/Baseline record generated from IUPAC 2021 \+ NIST ASD/g,'Initial baseline scaffold (superseded numeric claims; retained in Git history)');
 if(!text.includes('Source-backed baseline correction'))text+='\n| 1.1.0 | 2026-09-08 | Source-backed baseline correction: PubChem/CIAAW, null semantics, prediction labels |\n';
 return text;
}
export function identitySVG(el){return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 240" role="img"><title>'+el.name+' — '+el.matId+'</title><desc>Element identity card. This diagram is not an electron orbital or physical atom model.</desc><rect width="640" height="240" rx="12" fill="#142831"/><text x="32" y="46" fill="#bde4dc" font-family="sans-serif" font-size="16">'+el.matId+' · Z = '+el.z+'</text><text x="32" y="155" fill="#bde4dc" font-family="serif" font-size="95">'+el.symbol+'</text><text x="220" y="110" fill="#f5f1e8" font-family="serif" font-size="36">'+el.name+'</text><text x="220" y="150" fill="#bed0d3" font-family="sans-serif" font-size="18">Period '+el.period+' · '+el.category+'</text><text x="32" y="211" fill="#bed0d3" font-family="sans-serif" font-size="13">BASELINE · Consult the source-backed catalogue for properties and evidence.</text></svg>'}

