import {test,expect} from '@playwright/test';
test('homepage restores five environment references and preserved posters',async({page})=>{
 await page.goto('/');await expect(page.getByRole('heading',{name:'Explore the Materials Atlas'})).toBeVisible();await expect(page.locator('.composition-card')).toHaveCount(5);await expect(page.getByRole('heading',{name:'Your original visual references'})).toBeVisible();await expect(page.locator('.mat-home img')).toHaveCount(5);await expect(page.locator('.mat-home')).toContainText('Source verification pending');
});
test('canonical Hydrogen images occupy nine of twenty-two slots with resources and bookmarks',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Browse images & placeholders',exact:true}).click();await expect(page.locator('[data-panel-id]')).toHaveCount(22);await expect(page.locator('[data-panel-id] img')).toHaveCount(9);await expect(page.locator('.image-placeholder')).toHaveCount(13);for(const img of await page.locator('[data-panel-id] img').all()){await img.scrollIntoViewIfNeeded();await expect.poll(()=>img.evaluate((e:HTMLImageElement)=>e.complete&&e.naturalWidth>0)).toBe(true)}
 await expect(page.getByRole('region',{name:'Resources and citations'})).toBeVisible();await expect(page.getByRole('link',{name:'Open source ↗'}).first()).toHaveAttribute('href',/^https:\/\//);await page.getByRole('button',{name:'Bookmark',exact:true}).click();await expect(page.getByRole('button',{name:'Bookmarked',exact:true})).toBeVisible();await page.reload();await page.getByRole('button',{name:'Read the selected chapter',exact:true}).click();await expect(page.getByRole('button',{name:'Bookmarked',exact:true})).toBeVisible();
});
test('speech controls queue text and local translation produces a separate copy',async({page})=>{
 await page.addInitScript(()=>{const counts={speak:0,pause:0,resume:0,cancel:0};(window as any).__speech=counts;Object.defineProperty(window,'speechSynthesis',{value:{getVoices:()=>[],addEventListener:()=>{},removeEventListener:()=>{},speak:()=>counts.speak++,pause:()=>counts.pause++,resume:()=>counts.resume++,cancel:()=>counts.cancel++}});(window as any).Translator={availability:async()=> 'available',create:async()=>({translate:async(t:string)=>'TRADUIT '+t,destroy:()=>{}})}});
 await page.goto('/');await page.getByRole('button',{name:'Read the selected chapter',exact:true}).click();await page.getByRole('button',{name:'Read aloud',exact:true}).click();await page.getByRole('button',{name:'Pause',exact:true}).click();await page.getByRole('button',{name:'Resume',exact:true}).click();await page.getByRole('button',{name:'Stop audio',exact:true}).click();expect(await page.evaluate(()=>(window as any).__speech.speak)).toBe(1);
 await page.getByText('Translate chapter — separate reading copy',{exact:true}).click();await page.getByRole('button',{name:'Translate locally',exact:true}).click();await expect(page.locator('.translation-copy')).toContainText('TRADUIT');await expect(page.locator('.page')).not.toContainText('TRADUIT');
});
for(const [label,width,height]of [['mobile',390,844],['tablet',820,1180],['desktop',1500,1000]] as const)test(label+' reading layout keeps content and navigation reachable',async({page})=>{
 await page.setViewportSize({width,height});await page.goto('/');await expect(page.getByRole('heading',{name:'Explore the Materials Atlas'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);if(width<1200){await page.getByRole('button',{name:'Contents & search',exact:true}).click();await expect(page.getByRole('textbox',{name:'Find an element or chapter'})).toBeVisible();await page.locator('.elements-folder > summary').click();await page.getByRole('button',{name:'Open Hydrogen',exact:true}).click();await page.getByRole('button',{name:'Sources & bookmarks',exact:true}).click();await expect(page.getByRole('complementary',{name:'Chapter inspector'})).toBeVisible()}
});

test('chapter illustrations render at their sections and header returns home',async({page})=>{await page.goto('/');await page.getByRole('button',{name:'Read the selected chapter',exact:true}).click();await expect(page.locator('[data-inline-panel]')).toHaveCount(22);await expect(page.locator('[data-inline-panel] img')).toHaveCount(9);await expect(page.locator('[data-inline-panel="A06"]')).toContainText('Water');await page.getByRole('button',{name:'MAT home',exact:true}).click();await expect(page.getByRole('heading',{name:'Explore the Materials Atlas'})).toBeVisible();await page.screenshot({path:'../.mat-local/mat-restored-home.png',fullPage:false});});
