import {useEffect,useState} from 'react';
import {assetURL} from '../data-loader';
interface Dataset {title:string;subtitle:string;unit:string;conditions?:string;review_note?:string;data:{name:string;symbol:string;value:number}[]}
export function CompositionOverview(){
 const [sets,setSets]=useState<Record<string,Dataset>|null>(null),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();fetch(assetURL('book/data/chart-datasets.json'),{signal:c.signal}).then(r=>{if(!r.ok)throw Error('Composition reference could not load');return r.json()}).then(d=>setSets(d.abundanceDatasets)).catch(e=>{if(!c.signal.aborted)setError(String(e))});return()=>c.abort()},[]);
 const labels:Record<string,string>={universe:'Space & cosmic matter',crust:'Earth’s crust',human:'Human body',ocean:'Water & oceans',atmosphere:'Air & atmosphere'};
 return <section aria-label="Composition across environments"><h2>Elements around us</h2><p>Explore the earlier Earth, water, air, human-body and space composition tables. These preserved compilations still need source verification. Their historical percentages are available for comparison, but are not accepted scientific measurements in MAT.</p>{error&&<p role="alert">{error}</p>}{!sets&&!error&&<p>Loading composition references…</p>}<div className="image-grid">{sets&&Object.entries(sets).map(([id,d])=><section key={id} className="composition-card"><h3>{labels[id]||d.title}</h3><p>{d.title}</p><p>{d.subtitle}</p><strong>Source verification pending</strong><p>{id==='crust'?'Crust composition is not the composition of the whole Earth.':id==='ocean'?'Seawater includes dissolved salts; it is not pure H₂O.':id==='atmosphere'?'These are gas volume fractions, not elemental mass fractions.':id==='universe'?'Cosmic and Solar System compositions must be distinguished; these figures do not include dark matter or dark energy.':'Body composition varies by person and tissue.'}</p><details><summary>View preserved values — {d.unit}</summary><table><thead><tr><th>Constituent</th><th>Historical value</th></tr></thead><tbody>{d.data.map((r,i)=><tr key={i}><th>{r.name} ({r.symbol})</th><td>{r.value} {d.unit}</td></tr>)}</tbody></table>{d.review_note&&<p>{d.review_note}</p>}</details></section>)}</div><p><a href={assetURL('book/data/chart-datasets.json')} target="_blank" rel="noreferrer">Original composition datasets and review notes</a></p><p>Whole-Earth, pure-water, tissue-specific and other environment datasets need their own identified sources and conditions; they must not inherit these percentages.</p></section>
}
