import {useEffect,useState} from 'react';
import {assetURL} from '../data-loader';
interface Dataset {title:string;subtitle:string;unit:string;conditions?:string;review_note?:string;data:{name:string;symbol:string;value:number}[]}
export function CompositionOverview(){
 const [sets,setSets]=useState<Record<string,Dataset>|null>(null),[error,setError]=useState(''),[active,setActive]=useState('universe');
 useEffect(()=>{const c=new AbortController();fetch(assetURL('book/data/chart-datasets.json'),{signal:c.signal}).then(r=>{if(!r.ok)throw Error('Composition reference could not load');return r.json()}).then(d=>setSets(d.abundanceDatasets)).catch(e=>{if(!c.signal.aborted)setError(String(e))});return()=>c.abort()},[]);
 const labels:Record<string,string>={universe:'Space & cosmic matter',crust:'Earth’s crust',human:'Human body',ocean:'Water & oceans',atmosphere:'Air & atmosphere'};
 const d=sets?.[active];
 return <section className="composition-explorer" aria-labelledby="composition-title"><h2 id="composition-title">Elements around us</h2><p>Choose an environment to compare its main constituents.</p><div className="composition-choices" role="group" aria-label="Choose an environment">{Object.entries(labels).map(([id,label])=><button key={id} aria-pressed={active===id} onClick={()=>setActive(id)}>{label}</button>)}</div>{error&&<p role="alert">{error}</p>}{!sets&&!error&&<p role="status">Loading composition references…</p>}{d&&<div className="composition-chart" aria-live="polite"><h3>{labels[active]}</h3><p>{d.subtitle} · {d.unit}</p><p className="composition-review">Preserved reference values · source verification pending</p><p>{active==='crust'?'Crust composition differs from the whole Earth.':active==='ocean'?'Seawater includes dissolved salts; this is not pure water.':active==='atmosphere'?'Gas volume fractions, not elemental mass fractions.':active==='universe'?'Ordinary matter only. Dark matter and dark energy are excluded; cosmic and Solar System averages need separate verification.':'Body composition varies by person and tissue.'}</p><p className="composition-scale">Linear scale: 0–100%. Exact values remain visible for trace constituents.</p><ul aria-label={labels[active]+' composition, '+d.unit}>{[...d.data].sort((a,b)=>b.value-a.value).map((r,i)=><li key={i}><span className="composition-label">{r.name} <small>{r.symbol}</small></span><span className="composition-track" aria-hidden="true"><span style={{width:Math.max(0,Math.min(100,r.value))+'%'}}/></span><strong>{r.value}%</strong></li>)}</ul><details><summary>Values, conditions & source notes</summary><p>{d.conditions}</p><p>{d.review_note||'These legacy compilations remain unverified reference data, not accepted measurements or engineering design data.'}</p><table><caption>{labels[active]} — {d.unit}</caption><thead><tr><th>Constituent</th><th>Value</th></tr></thead><tbody>{d.data.map((r,i)=><tr key={i}><th>{r.name} ({r.symbol})</th><td>{r.value} {d.unit}</td></tr>)}</tbody></table><a href={assetURL('book/data/chart-datasets.json')} target="_blank" rel="noreferrer">Original datasets and provenance notes</a></details></div>}</section>
}
