import {useEffect,useState} from 'react';
import {assetURL} from '../data-loader';
interface Panel {panel_id:string;reference_label:string;locked_visual_slots:string[];asset_path?:string|null;status:string;source_ids?:string[];review?:string}
interface Plan {elements:{record_id:string;panels:Panel[]}[]}
export function ElementImages({id,name,assets,onNotes}:{id:string;name:string;assets:string[];onNotes:()=>void}){
 const [plan,setPlan]=useState<Plan|null>(null),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();fetch(assetURL('data/quality/panel-image-plan.json'),{signal:c.signal}).then(r=>{if(!r.ok)throw Error('Image register could not load');return r.json()}).then(setPlan).catch(e=>{if(!c.signal.aborted)setError(String(e))});return()=>c.abort()},[]);
 const panels=plan?.elements.find(e=>e.record_id===id)?.panels;
 return <section className="image-library"><h2>{name} — images & placeholders</h2><p>Two sets: nine light educational panels and thirteen dark blueprint panels. Existing images remain available; further generation is deferred while scientific data is completed.</p><button onClick={onNotes}>Read image descriptions & source notes</button>{error&&<p role="alert">{error}</p>}{!plan&&!error&&<p role="status">Loading image register…</p>}{plan&&!panels&&<p>No 22-panel element plan applies to this reference chapter.</p>}{['A','B'].map(set=><section key={set}><h3>{set==='A'?'Set A — light educational panels':'Set B — dark blueprint panels'}</h3><div className="image-grid">{panels?.filter(p=>p.panel_id.startsWith(set)).map(p=><figure key={p.panel_id} id={id.replace(':','-')+'-'+p.panel_id} data-panel-id={p.panel_id}><figcaption><strong>{p.panel_id} — {p.reference_label}</strong><small>Canonical slot: {id}:{p.panel_id} · {p.locked_visual_slots.join(', ')}</small></figcaption>{p.asset_path?<a href={assetURL(p.asset_path)} target="_blank" rel="noreferrer"><img src={assetURL(p.asset_path)} alt={name+' '+p.panel_id+': '+p.reference_label} loading="lazy"/></a>:<div className="image-placeholder">Image pending<br/><small>Placeholder retained · data-first work in progress</small></div>}<p>{p.review||'The element-specific content and evidence must be reviewed before this slot is completed. The title follows the Hydrogen design reference and is adapted for the selected element.'}</p>{p.source_ids?.length?<p>Sources: {p.source_ids.join(', ')}</p>:null}</figure>)}</div></section>)}<details open><summary>Existing figures, charts & other visual references</summary><div className="image-grid">{assets.filter(p=>/\.(svg|png|jpe?g|webp)$/i.test(p)&&!panels?.some(s=>s.asset_path===p)).map(p=><figure key={p}><a href={assetURL(p)} target="_blank" rel="noreferrer"><img loading="lazy" src={assetURL(p)} alt={p.split('/').pop()}/></a><figcaption>{p.split('/').pop()}</figcaption></figure>)}</div></details></section>
}
