import {useEffect,useMemo,useState} from 'react';
import {assetURL} from '../data-loader';
type Entry={entry_id:string;label:string;source_id:string;dataset:string;topic_candidates:string[]};
export function FrequencyExplorer({onGuide}:{onGuide:()=>void}){
 const [entries,setEntries]=useState<Entry[]>([]),[query,setQuery]=useState(''),[topic,setTopic]=useState('all'),[page,setPage]=useState(0),[error,setError]=useState(''),[detail,setDetail]=useState<Record<string,unknown>|null>(null),[selected,setSelected]=useState<Entry|null>(null),[busy,setBusy]=useState(false);
 useEffect(()=>{const c=new AbortController();fetch(assetURL('data/research/frequency-reference-index.json'),{signal:c.signal}).then(r=>{if(!r.ok)throw Error('Frequency index could not load');return r.json()}).then(d=>setEntries(d.entries)).catch(e=>{if(!c.signal.aborted)setError(String(e))});return()=>c.abort()},[]);
 useEffect(()=>{setDetail(null);if(!selected)return;const c=new AbortController();setBusy(true);setError('');fetch(assetURL('data/research/'+selected.dataset),{signal:c.signal}).then(r=>{if(!r.ok)throw Error('Source dataset could not load');return r.json()}).then(d=>{if(!c.signal.aborted){setDetail(d.entries.find((r:{id:string})=>r.id===selected.entry_id));setBusy(false)}}).catch(e=>{if(!c.signal.aborted){setError(String(e));setBusy(false)}});return()=>c.abort()},[selected]);
 const filtered=useMemo(()=>entries.filter(e=>(topic==='all'||e.topic_candidates.includes(topic))&&(e.label+' '+e.source_id).toLowerCase().includes(query.toLowerCase())),[entries,query,topic]);
 return <section className="frequency-explorer"><h1>Frequency research library</h1><p>Search publisher references across substances, organisms and body systems. Topic labels are search aids awaiting review. Listed associations are not established measurements or treatment instructions.</p><button onClick={onGuide}>Compare hospital, technology & science metrics</button><div className="controls"><label>Search references<input value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}} placeholder="Name, substance, organism or source ID"/></label><label>Topic<select value={topic} onChange={e=>{setTopic(e.target.value);setPage(0)}}>{['all','plant','animal','body-system','organism','organic-substance','unclassified'].map(t=><option key={t}>{t}</option>)}</select></label></div><p role="status">{entries.length?`${filtered.length.toLocaleString()} matching source entries`:'Loading references…'}</p>{error&&<p role="alert">{error}</p>}<ul className="frequency-results">{filtered.slice(page*30,(page+1)*30).map(e=><li key={e.entry_id}><button onClick={()=>setSelected(e)} aria-pressed={selected?.entry_id===e.entry_id}>{e.label}</button><small>{e.source_id} · {e.topic_candidates.join(', ')}</small></li>)}</ul><div className="controls"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous results</button><span>Page {page+1} of {Math.max(1,Math.ceil(filtered.length/30))}</span><button disabled={(page+1)*30>=filtered.length} onClick={()=>setPage(p=>p+1)}>Next results</button></div>{selected&&<section aria-live="polite"><h2>{selected.label}</h2>{busy?<p>Loading source details…</p>:detail&&<><p><strong>Publisher claim · unit UNKNOWN</strong></p><p>Source: {selected.source_id} · PDF page(s): {String(detail.pdf_page||detail.pdf_pages)}</p><p>Printed tokens: <strong className="frequency-tokens">{String(detail.frequencies_raw||detail.frequency_tokens_raw)}</strong></p><p>Database code: {String(detail.publisher_database_code)}. Operators and suffixes retain their source syntax; they are not automatically interpreted as frequencies or durations.</p><details><summary>Provenance and structured values</summary><pre>{JSON.stringify(detail,null,2)}</pre></details><a href={assetURL('data/research/sources/'+(selected.source_id==='SRC-000309'?'spooky2-frequency-list-2021.pdf':'spooky2-frequency-list-2015.pdf'))+'#page='+String(detail.pdf_page||(detail.pdf_pages as number[])?.[0]||1)} target="_blank" rel="noreferrer">Read the original PDF at this entry</a><br/><a href={assetURL('data/research/'+selected.dataset)} target="_blank" rel="noreferrer">Open source-linked dataset</a></>}</section>}</section>
}
