import {useEffect,useRef,useState} from 'react';
interface LocalTranslator {translate:(text:string)=>Promise<string>;destroy:()=>void}
interface TranslationAPI {availability:(o:{sourceLanguage:string;targetLanguage:string})=>Promise<string>;create:(o:{sourceLanguage:string;targetLanguage:string})=>Promise<LocalTranslator>}
export function ReadingTools({body,size,onSize}:{body:string;size:number;onSize:(n:number)=>void}){
 const [voices,setVoices]=useState<SpeechSynthesisVoice[]>([]),[voice,setVoice]=useState(''),[rate,setRate]=useState(1),[status,setStatus]=useState(''),[target,setTarget]=useState('fr'),[translation,setTranslation]=useState(''),[busy,setBusy]=useState(false);
 const epoch=useRef(0),alive=useRef(true);
 const speech=typeof window!=='undefined'&&'speechSynthesis'in window;
 const api=(globalThis as typeof globalThis&{Translator?:TranslationAPI}).Translator;
 useEffect(()=>{alive.current=true;const update=()=>setVoices(speech?window.speechSynthesis.getVoices():[]);update();if(speech)window.speechSynthesis.addEventListener('voiceschanged',update);return()=>{alive.current=false;epoch.current++;if(speech){window.speechSynthesis.cancel();window.speechSynthesis.removeEventListener('voiceschanged',update)}}},[speech]);
 const stop=()=>{epoch.current++;if(speech)window.speechSynthesis.cancel();setStatus('Stopped')};
 const read=()=>{if(!speech)return;window.speechSynthesis.cancel();const run=++epoch.current;const plain=body.replace(/```[\s\S]*?```/g,' [Structured data omitted from speech] ').replace(/!\[([^\]]*)\]\([^)]*\)/g,'$1').replace(/\[([^\]]*)\]\([^)]*\)/g,'$1').replace(/[#*_`]/g,'');const chunks=plain.match(/[\s\S]{1,1000}(?:\s|$)/g)||[plain];let index=0;const next=()=>{if(run!==epoch.current||!alive.current)return;if(index>=chunks.length){setStatus('Reading finished');return;}const u=new SpeechSynthesisUtterance(chunks[index++]);u.rate=rate;u.lang='en';u.voice=voices.find(v=>v.voiceURI===voice)||null;u.onend=next;u.onerror=()=>{if(run===epoch.current)setStatus('Speech failed or was interrupted. Choose another available voice.');};window.speechSynthesis.speak(u)};setStatus('Reading aloud');next()};
 async function translate(){if(!api)return;setBusy(true);setTranslation('');setStatus('Checking local translation model…');let translator:LocalTranslator|undefined;try{const options={sourceLanguage:'en',targetLanguage:target};if(await api.availability(options)==='unavailable')throw Error('This language pair is unavailable in this browser.');if(alive.current)setStatus('Preparing translation. The browser may download a language model.');translator=await api.create(options);const parts=body.split(/(```[\s\S]*?```|\$\$[\s\S]*?\$\$)/g);const output=[];for(const part of parts){if(!alive.current)return;if(part.startsWith('```')||part.startsWith('$$')||!part.trim()){output.push(part);continue;}for(const paragraph of part.split(/\n\n/)){if(!alive.current)return;output.push(paragraph.trim()?await translator.translate(paragraph):paragraph)}}if(alive.current){setTranslation(output.join('\n\n'));setStatus('Machine translation ready — unreviewed; check terminology and values against the original.')}}catch(e){if(alive.current)setStatus(String(e))}finally{translator?.destroy();if(alive.current)setBusy(false)}}
 return <section className="reading-tools" aria-label="Reading and accessibility tools"><h2>Reading tools</h2><div className="controls"><label>Text size<select value={size} onChange={e=>onSize(Number(e.target.value))}>{[14,16,18,20,22,24].map(n=><option key={n} value={n}>{n} px</option>)}</select></label><label>Voice<select value={voice} onChange={e=>setVoice(e.target.value)}><option value="">System default</option>{voices.map(v=><option key={v.voiceURI} value={v.voiceURI}>{v.name} · {v.lang}</option>)}</select></label><label>Reading speed<select value={rate} onChange={e=>setRate(Number(e.target.value))}>{[0.75,1,1.25,1.5,2].map(n=><option key={n} value={n}>{n}×</option>)}</select></label><button disabled={!speech} onClick={read}>Read aloud</button><button disabled={!speech} onClick={()=>{window.speechSynthesis.pause();setStatus('Paused')}}>Pause</button><button disabled={!speech} onClick={()=>{window.speechSynthesis.resume();setStatus('Reading aloud')}}>Resume</button><button disabled={!speech} onClick={stop}>Stop audio</button><button onClick={()=>window.print()}>Print / Save PDF</button></div><p>{speech?'Uses available system/browser voices. Formula pronunciation may need checking.':'Speech synthesis is unavailable in this browser.'}</p><details><summary>Translate chapter — separate reading copy</summary><p>Machine translation is unreviewed. Scientific identifiers, units and terminology must be checked against the original. Canonical records and local drafts are never overwritten. Code blocks and display equations are preserved.</p><label>Translation language<select disabled={busy} value={target} onChange={e=>{setTarget(e.target.value);setTranslation('')}}>{[['fr','French'],['es','Spanish'],['de','German'],['it','Italian'],['pt','Portuguese'],['ja','Japanese'],['zh','Chinese']].map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><button disabled={!api||busy} onClick={translate}>{busy?'Translating…':'Translate locally'}</button>{!api&&<p role="note">Local chapter translation is not available in this browser. A browser supporting the built-in Translator API is required; no translation has been produced.</p>}{translation&&<div className="translation-copy" lang={target}><h3>Unreviewed machine translation</h3><p style={{whiteSpace:'pre-wrap'}}>{translation}</p></div>}</details><p role="status">{status}</p></section>
}
